; SPDX-License-Identifier: GPL-2.0-or-later
; ARI for pbx-brain. http.conf must bind 127.0.0.1 only —
; ARI is never exposed past localhost.
[general]
enabled = yes
pretty = yes

[pbxbrain]
type = user
read_only = no
password = CHANGE_ME_AT_INSTALL
