# SPDX-License-Identifier: GPL-2.0-or-later
# Fail2ban filter: a flood detected by the edge's pike rate limit
# (more than ~30 requests in 2 seconds from one IP).

[Definition]
failregex = ^.*kamailio\[\d+\]: WARNING: .*edge: flood from <HOST>\s*$

ignoreregex =
