# SPDX-License-Identifier: GPL-2.0-or-later
# Fail2ban filter for the own-pbx Kamailio edge proxy.
# Matches: dropped SIP scanners, sanity failures, failed sign-ins (a phone
# account's password was sent and refused) and non-TLS attempts.
# Normal 401 challenges (every phone gets one before sending its password)
# are NOT logged by the edge, so they never count here.
# Tolerant prefix: journal lines look like
#   "host /usr/sbin/kamailio[123]: WARNING: <script>: edge: ..."

[Definition]
failregex = ^.*kamailio\[\d+\]: WARNING: .*edge: dropping scanner .* from <HOST>\s*$
            ^.*kamailio\[\d+\]: WARNING: .*edge: sanity check failed from <HOST>.*$
            ^.*kamailio\[\d+\]: WARNING: .*edge: auth failed for \S+ user .* from <HOST>\s*$
            ^.*kamailio\[\d+\]: WARNING: .*edge: refusing non-TLS initial \S+ from <HOST>\s*$

ignoreregex =
