# SPDX-License-Identifier: GPL-2.0-or-later
# Report fail2ban bans/unbans to the own-pbx panel (dashboard Activity feed
# + email alert). Never blocks or fails the ban itself.

[Definition]
norestored = true
actionstart =
actionstop =
actioncheck =
actionban = /usr/local/sbin/pbx-edge-notify ban <ip> <name> <failures> <bantime>
actionunban = /usr/local/sbin/pbx-edge-notify unban <ip> <name> 0 0

[Init]
name = default
